name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${tag#v}" >> $GITHUB_OUTPUT
        env:
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          version: ${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}